### PR TITLE
fix(.github): use GitHub app to get token for pushing

### PR DESCRIPTION
**Pull request by michaelbeaumont**
Right now none of the GH actions run for these PRs.

### CODE REVIEW

**Review by bartsmykla — APPROVED** [review]
lgtm

**Comment by lahabana** [comment]
Hmm actually #920 ran actions no?

**Comment by michaelbeaumont** [comment]
@lahabana because I pushed a new commit

**Comment by lahabana** [comment]
Anyway in any case the app will give nicer commiter than "github-actions" and will enable a bunch of other nicer things that not having an app limited us to do.

**Pull request merged**
