### PR TITLE
feat(mermaid): Add Mermaid.js diagrams plugin

### PR DESCRIPTION
**Pull request by cloudjumpercat**
The docs team recently added [Mermaid.js](https://mermaid.js.org/) to our own docs repo ([see PR here](https://github.com/Kong/docs.konghq.com/pull/6438)) to make it easy to create diagrams. We also added some custom styles to match our branding colors. I thought it would make a nice addition to the Kuma repo, and I have a doc that I'm writing that would benefit from this diagram tool.

It can be used with the following syntax: 
```
{% mermaid %}
{% endmermaid %}
```
 
 With mermaid we can describe graphs and diagrams in a markdown file and have them render as what we want. 
 So 
 ```
{% mermaid %}
 gantt
    title Git Issues - days since last update
    dateFormat  X
    axisFormat %s

    section Issue19062
    71   : 0, 71
    section Issue19401
    36   : 0, 36
    section Issue193
    34   : 0, 34
    section Issue7441
    9    : 0, 9
    section Issue1300
    5    : 0, 5
{% endmermaid %}
```

would render as:
image

We've been using https://mermaid.live/edit to easily generate diagrams and see the rendered output before adding it to docs.

Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits) Yes

Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)? Yes

### CODE REVIEW

**Comment by cloudjumpercat** [comment]
The docs team added this to our stylesheet: https://github.com/Kong/docs.konghq.com/blob/e2f6df6b7f639891c59aad47b54ffe83c752c94b/app/_assets/stylesheets/page.less#L346

But I wasn't sure where to put that in the kuma-website style sheet.

**Comment by cloudjumpercat** [comment]
I need to delete this edit before this PR is merged, but here's an example of how a flowchart would currently render in the Kuma docs: https://deploy-preview-1547--kuma.netlify.app/docs/2.5.x/introduction/about-service-meshes/

**Comment by lena-larionova** [comment]
I think you should be able to set it here, to fix the styling:
https://github.com/cloudjumpercat/kuma-website/blob/feat/mermaid-js/app/_assets/styles/custom/base/_type-and-content.scss#L89-L98C6

This should work:
```css
  pre,
  pre[class*='language-'],
  div[class*='language-'] {
    background-color: $codeBgColor;

    &.mermaid {
      background-color: unset;
    }

    code {
      font-size: 0.9rem;
      line-height: 1.5;
      color: #333;
    }
  }
```

If that doesn't work, then you can do it like this:

```css
  pre,
  pre[class*='language-'],
  div[class*='language-'] {
    background-color: $codeBgColor;

    code {
      font-size: 0.9rem;
      line-height: 1.5;
      color: #333;
    }
  }

 pre.mermaid {
      background-color: unset;
  }
```

**Comment by cloudjumpercat** [comment]
@lena-larionova Thanks for the feedback! You're first suggestion fixed it!

**Comment by cloudjumpercat** [comment]
I removed the test example so I can mark this PR as ready, but here's an image of what it looked like when rendered:
Screenshot 2023-12-07 at 8 59 33 AM

**Review by slonka — COMMENTED** [review]
Hi! :) We already have some diagrams like this one 
image
and a policy to make the diagrams https://github.com/kumahq/kuma-website/blob/58bbbacaac6aa63bf9241a3e98495cfa99378122/WRITING-DOCUMENTATION.md?plain=1#L28 ( https://docs.google.com/presentation/d/1qvIKeYfcuowrHW1hV9fk9mCptt3ywroPBUYFjMj9gkk/edit#slide=id.g13d0c1ffb72_0_67 ). I don't think we should have two ways of making diagrams and I don't think it's worth going through all of them and converting them to mermaid.

**Comment by lahabana** [comment]
I'm ok with this but should plugins like this be extracted away to be consumable as a dependency? this duplication seems to be the open door to future maintainance issues.

Can we start using it somewhere? I think it'd make it easier to review :)

Also is it ok to rely on a CDN for the mermaid lib?

@fabianrbz WDYT?

**Comment by fabianrbz** [comment]
> I think this is very welcome! Lowering the bar of adding graph and charts is a great idea! However, should plugins like this be extracted away to be consumable as a dependency? this duplication seems to be the open door to future maintainance issues.

We can, however, we wouldn't be gaining much tbh. 

> Can we start using it somewhere? I think it'd make it easier to review :)

We have a few [examples](https://github.com/Kong/docs.konghq.com/blob/62495a9d5d8b38cc7ed59b77e4ad356cfd91b9b2/app/_includes/md/gateway/hybrid-upgrade.md?plain=1#L31) in docs.konghq


> Also is it ok to rely on a CDN for the mermaid lib?

It should be ok, it's what they use in their docs.

> @fabianrbz WDYT?

It's the same implementation we have in docs.konghq, I'm trying to improve it so that the script doesn't get included with every diagram (we could have several diagrams on one page). I also don't want to include the mermaid js on every page.
I'll get back to you on this

**Review by lahabana — APPROVED** [review]

**Comment by lahabana** [comment]
@cloudjumpercat can you rebase you first commit so it's Signed-Off too? (or just squash all your commits).

**Comment by bartsmykla** [comment]
@cloudjumpercat all looks good now, thank you!

**Pull request merged**
