### PR TITLE
proxy template modifications

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**

### CODE REVIEW

**Comment by nickolaev** [comment]
Will it make sense to not use `test`, like in `test-cluster` and `x-header: test`? Maybe replace it with `backend` or something that sounds more "production" ready.

**Comment by jakubdyszkiewicz** [comment]
If I'm matching `backend` dataplane there is probably `backend` cluster already 🤔  any ideas for different name?

**Comment by nickolaev** [comment]
`development`, `staging`, `production`?

**Comment by jakubdyszkiewicz** [comment]
environment does not make sense IMHO. I can't find better names. Merging it now to have docs live, we can improve names in separate PR.

**Pull request merged**
