### PR TITLE
Fix common redirects

### PR DESCRIPTION
**Pull request by fabianrbz**
Remove a malformed redirect and move `/docs/latest/* /docs/LATEST_RELEASE/:splat 302` from `_common_redirects` to `_redirects`. We use `/latest/` in konghq for our docs.

**Note**:
There are a few redirects that are only valid for a few versions that we definitely want to fix, e.g.:

* `/docs/:version/other/ /docs/:version/other/enterprise 301` is only valid for versions 1.1.x to 1.5.x, should it redirect to `/introduction/enterprise` for newer versions?
* `/docs/:version/api/ /docs/:version/documentation/http-api 301`  ` is only valid for versions 1.1.x to 1.5.x, it should redirect to `/reference/http-api` for newer versions

Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits) Yes

Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)? Yes

### CODE REVIEW

**Comment by fabianrbz** [comment]
@lahabana I don't know what those failures are about, but they seem unrelated to the changes

**Comment by lahabana** [comment]
Likely not your fault it seems like an external link moved: https://gateway-api.sigs.k8s.io/geps/gep-713/ (used to be geps/geps/gep-713)

**Comment by fabianrbz** [comment]
we could add a similar implementation to the `moved_urls` that we have in kong for fixing the issues mentioned in the **Note**
should I fix the external link as part of this PR?

**Comment by lahabana** [comment]
Ha yes that's cool we should do this!

**Comment by slonka** [comment]
@lahabana 

I'm taking

> Ha yes that's cool we should do this!

as an approve here :) I'll review and approve and merge if everything is ok.

**Review by slonka — APPROVED** [review]

**Pull request merged**
