### PR TITLE
feat(upgrade): embed upgrade.md in docs

### LINKED ISSUE #1535: add UPGRADE.md in docs
### Description

It's synced from kumahq/kuma so it would be nice to have it embedded in the website too

### PR DESCRIPTION
**Pull request by lahabana**
Fix #1535

<Explain your change!>

Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits)

Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Review by michaelbeaumont — APPROVED** [review]

**Review by slonka — APPROVED** [review]
LGTM, but do we now need to use template variables in https://github.com/kumahq/kuma/blob/master/UPGRADE.md so that it renders correctly on both websites?

**Comment by slonka** [comment]
Rendered: https://deploy-preview-1706--kuma.netlify.app/docs/2.6.x/production/upgrades-tuning/upgrade-notes/

also some links are broken, should we disable link checker on this page?

**Comment by lahabana** [comment]
> also some links are broken, should we disable link checker on this page?

I think we'd be better off fixing the links.

For the variable the UPGRADE pages are different between Kuma and KM and the one from KM will link to the Kuma docs (see: https://github.com/Kong/kong-mesh/blob/master/UPGRADE.md). It was an easy low effort change.
In the future we may want to make these pages better but at least now we have this info on the docs website (perfect is the enemy of good :) )

**Comment by lahabana** [comment]
This should fix the links: https://github.com/kumahq/kuma/pull/9835

**Comment by slonka** [comment]
CoreDNS website timed out on the last link check and there is a problem with GH anchor that was fixed in main. Let's see if merge fixes it.

**Comment by slonka** [comment]
For the links issue: https://github.com/kumahq/kuma-website/pull/1712/files

**Pull request merged**
