### PR TITLE
Fix Traffic Metric Policy in universal mode doc

### LINKED ISSUE #295: Can't see metrics data at Grafana dashboard with Quickstart in Universal Mode
hi, I'm trying to use kuma-demo with universal mode following to https://kuma.io/docs/0.7.2/quickstart/universal/ .
I did step by step "1. Run the Marketplace application" -> "2. Enable Mutual TLS and Traffic Permissions" -> "3. Visualize Traffic Metrics" but when I try to see Grafana dashboard at http://192.168.33.80:3000 , Grafana dashboard itself is shown, but there is no metrics data. And also when I checked Prometheus dashboard at http://192.168.33.80:9090/targets , all targets are down with error message "read: connection reset by peer".
capture20201014

Then, I applied below Traffic Metric Policy following to https://github.com/kumahq/kuma-demo/blob/master/vagrant/README.md#traffic-metrics , Ican see metric data at Grafana dashboard.
```
$ cat <<EOF | kumactl apply -f -
type: Mesh
name: default
mtls:
  enabledBackend: ca-1
  backends:
  - name: ca-1
    type: builtin
metrics:
  enabledBackend: prometheus-1
  backends:
  - name: prometheus-1
    type: prometheus
    conf:
      skipMTLS: true
EOF
```

So, I think this doc https://kuma.io/docs/0.7.2/quickstart/universal/ causes misunderstanding. IMO it's better to replace with above manifest in "3. Visualize Traffic Metrics". How do you think?

My enviroment:
- OS: Ubuntu 18.04
- mode: Universal mode
- kuma version; 0.7.2

### PR DESCRIPTION
**Pull request by YuikoTakada**
Signed-off-by: YuikoTakada <y-mori@ti.jp.nec.com>

Fix #295

### CODE REVIEW

**Review by nickolaev — APPROVED** [review]

**Comment by nickolaev** [comment]
Can you also have this updated for `0.7.1` and `0.7.2`?

**Comment by YuikoTakada** [comment]
@nickolaev sure. I cannot find docs path of 0.7.1 and 0.7.2. Could you please tell me?

**Comment by nickolaev** [comment]
> @nickolaev sure. I cannot find docs path of 0.7.1 and 0.7.2. Could you please tell me?

https://github.com/kumahq/kuma-website/blob/master/docs/docs/0.7.1/quickstart/universal.md
https://github.com/kumahq/kuma-website/blob/master/docs/docs/0.7.2/quickstart/universal.md

**Comment by subnetmarco** [comment]
Thanks! @YuikoTakada

**Pull request merged**
