### PR TITLE
chore: install netlify-cli in project instead of globally

### PR DESCRIPTION
**Pull request by kleinfreund**
Install the netlify-cli package in the project instead of globally.

Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>

Note: the packages in package.json are _very_ outdated. It doesn’t look like we’re using Dependabot here.

### CODE REVIEW

**Review by johncowen — APPROVED** [review]
Thanks!

**Comment by johncowen** [comment]
Oh actually, could you have a look and see where else netlify is mentioned in the project? I think there are a couple of other places that should now use `serve` or `yarn dev`

**Comment by kleinfreund** [comment]
> Oh actually, could you have a look and see where else netlify is mentioned in the project? I think there are a couple of other places that should now use `make serve` or `yarn dev`

I did and I could only find this one instance. Have I missed any that you know of?

**Comment by kleinfreund** [comment]
@johncowen just pinging you in case you missed this. If you don’t know of any more instances that I haven’t found, I’ll merge this in a while.

**Comment by kleinfreund** [comment]
> Does the one in the `Procfile` need changing?

Ah, interesting. I didn’t find this because I’ve already had the netlify line removed for a long time locally (I needed that for some reason to workaround some issue) and so didn’t consider it at all. I’ve updated it now.

**Comment by johncowen** [comment]
Ok cool, can you ping someone else to check this real quick, the JS here is fine by me, but I'm not totally sure about the Procfile and what its used for etc (especially seeing as you didn't need it locally)

**Comment by kleinfreund** [comment]
> Ok cool, can you ping someone else to check this real quick, the JS here is fine by me, but I'm not totally sure about the Procfile and what its used for etc (especially seeing as you didn't need it locally)

@fabianrbz Could you have a look at this, please?

**Review by fabianrbz — APPROVED** [review]

**Comment by johncowen** [comment]
thanks @fabianrbz 👍

**Pull request merged**
