### PR TITLE
docs(*): add "kuma.io/sidecar-drain-time" k8s annotation

### PR DESCRIPTION
**Pull request by lobkovilya**
Signed-off-by: Ilya Lobkov <ilya.lobkov@konghq.com>

### CODE REVIEW

**Review by lahabana — COMMENTED** [review]
Is this new or does it need to be backported to older docs?

**Comment by lobkovilya** [comment]
Right, needs to be backported to Kuma 1.8

**Comment by lahabana** [comment]
@lobkovilya please finish that up :)

**Comment by slonka** [comment]
I took the liberty of backporting this to `1.8` - if you want me not to do that let me know. I meant no ill intent - just wanted to move this PR forward since I know you're busy with other things.

**Review by slonka — APPROVED** [review]

**Pull request merged**
