### PR TITLE
Updated Red Hat Logo and Text

### LINKED ISSUE #970: [Bug] - Updated Red Hat Logo and Name
### What happened?

**Description:**

The Red Hat logo on this page, https://kuma.io/install/latest/ is outdated according to the brand guidelines https://www.redhat.com/en/about/brand/standards/logo and needs to be updated to the new one

Screenshot 2022-08-19 at 3 07 18 PM

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

- Updated the Red Hat Logo and Text according to Red Hat brand guidelines at, https://www.redhat.com/en/about/brand/standards/logo

Screenshot 2022-08-19 at 3 10 57 PM

Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits) - Yes

Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)? - Yes

Fix #970

### CODE REVIEW

**Comment by kleinfreund** [comment]
Wouldn’t [logo variant C](https://www.redhat.com/en/about/brand/standards/logo?pfe-1v68z18rn=logo-c) fit in this space much nicer? All the other logos on this page are square and so is logo C.

**Comment by slonka** [comment]
Also, make sure that the PNG is optimized with `optipng` or something similar. Here is the optimized version (50% smaller size):

logo-redhat

**Comment by adithyaakrishna** [comment]
@slonka Optimized and Updated ✅ 

@kleinfreund Yes, there was just the Fedora which would have suited better but I thought to go with this one as it kinda looks neat on the site as well 😶

**Comment by lahabana** [comment]
@adithyaakrishna as @kleinfreund pointed out variant C is more coherent with the rest of this page

**Comment by adithyaakrishna** [comment]
@lahabana My bad, apologies for the confusion, I had mistaken it for some other variant that had the logo next to the Red Hat text. I have updated the MR with the correct one as well :)

**Review by bartsmykla — APPROVED** [review]
lgtm

**Review by kleinfreund — APPROVED** [review]
Thank you. That looks good to me, too.

**Pull request merged**
