### PR TITLE
Move to Jekyll

### PR DESCRIPTION
**Pull request by mheap**
Replace Vuepress with Jekyll. Most of this work was done by @fabianrbz - I squashed all commits and am submitting the PR as he's on PTO.

Signed-off-by: Michael Heap <m@michaelheap.com>

Did you sign your commit? Yes

Have you read [Contributing guidelines] Yes

### CODE REVIEW

**Comment by mheap** [comment]
@johnharris85 One more week, then yes! Will let you know when

**Comment by slonka** [comment]
Should we be reviewing this or is this WIP?

**Review by jakubdyszkiewicz — APPROVED** [review]

**Comment by kleinfreund** [comment]
**Suggestion (trivial)**: the copy button in code blocks partially occludes the code block language text. The copy button can be moved down relative to the code block a bit to avoid this.

**Comment by lahabana** [comment]
One thing to not forget before merging is to update `WRITING_DOCUMENTATION.md`

**Comment by mheap** [comment]
@lahabana `WRITING_DOCUMENTATION.md` updated

@kleinfreund Definitely worth fixing both. I'd like to ship the replatform to unblock other teams, then submit followup quality of life PRs if you agree

**Comment by kleinfreund** [comment]
@mheap That’s perfectly fine for me. I’ve submitted separate issues for them:

* https://github.com/kumahq/kuma-website/issues/1057
* https://github.com/kumahq/kuma-website/issues/1058

**Pull request merged**
