### PR TITLE
doc: fix formatting for kuma.io/ignore example

### PR DESCRIPTION
**Pull request by vbelouso**
just a fix for typo error

### CODE REVIEW

**Comment by vbelouso** [comment]
in version 1.5 the same typo error

**Comment by jakubdyszkiewicz** [comment]
Hey @vbelouso please sign DCO, thank you!

**Comment by lahabana** [comment]
You can also backport this change to 1.5.x with: https://github.com/kumahq/kuma-website/blob/master/WRITING-DOCUMENTATION.md#fixing-typos `./backport.sh dev 1.5.x`

**Comment by lahabana** [comment]
Replaced by: #798

**Pull request closed without merging**
