### PR TITLE
cleanup: removed old scripts and rely on docs/config.js for config

### PR DESCRIPTION
**Pull request by lahabana**
These changes are done in order to make the setup of the website simpler and avoid
repetition.
The goal is to make releasing a new version just a copy paste of a folder.

- remove kumacut (unused)
- remove docs/.partials (unused)
- remove unused md plugin for include
- rewrite config to read the list of versions from the directories instead of `releases.json`
- split navbar in each docs folder to make it easier to find
- identify the latest version with a `.latest` marker file
- generate netlify redirect and headers in vuepress script not as a bin/ script
- generate releases.json, latest_version.html and manifest in a vuepress plugin instead of
a home grown script

Signed-off-by: Charly Molter <charly.molter@konghq.com>

### CODE REVIEW

**Comment by Bradamant3** [comment]
hah I started working on the related bits of the readme last night. Hosed my local build environment in the process bc kumacut :-(

**Review by Bradamant3 — APPROVED** [review]
Maybe somebody else wants to test? (bc I can't at this point ...) but approving ahead of whatever y'all want to do. AWESOME.

**Comment by lahabana** [comment]
Still trying to figure out a bug in sidebar

**Comment by lahabana** [comment]
Looks like it's all good. Will get some test-friday time to have everyone check this

**Pull request merged**
