### PR TITLE
doc(kuma-cp) health check jitter

### PR DESCRIPTION
**Pull request by lobkovilya**
Docs for https://github.com/kumahq/kuma/pull/1570

### CODE REVIEW

**Review by Bradamant3 — CHANGES_REQUESTED** [review]
Can you please remove the change to `package-lock.json` from the PR? Thanks!

**Comment by lobkovilya** [comment]
@Bradamant3 yep, it was unintentionally :) Fixed

**Review by Bradamant3 — APPROVED** [review]
LGTM

**Comment by Bradamant3** [comment]
@lobkovilya we need to get this into the 1.0.8 docs too, right? I can take if it helps.

**Comment by nickolaev** [comment]
@Bradamant3 yes, this is for 1.0.8

**Pull request merged**
